Repository MJU-Capstone-Album2Me/REPOST-Backend, pull requests merged in 2023-06, with the labels that each got.

#82 refactor: 룸 전체 조회 api 멤버 수 추가
  src/main/java/com/album2me/repost/domain/room/dto/response/RoomResponse.java
  src/main/java/com/album2me/repost/domain/room/model/Room.java
  src/main/java/com/album2me/repost/domain/room/service/RoomService.java
  src/main/resources/application.yml
Labels: ♻️ refactor

#86 feat: 프로필 사진 등록 기능 구현
  src/main/java/com/album2me/repost/domain/image/service/ImageService.java
  src/main/java/com/album2me/repost/domain/post/service/PostService.java
  src/main/java/com/album2me/repost/domain/room/controller/RoomController.java
  src/main/java/com/album2me/repost/domain/user/controller/UserController.java
  src/main/java/com/album2me/repost/domain/user/dto/request/UserProfileChangeRequest.java
  src/main/java/com/album2me/repost/domain/user/dto/response/UserProfileChangeResponse.java
  src/main/java/com/album2me/repost/domain/user/model/User.java
  src/main/java/com/album2me/repost/domain/user/service/UserService.java
Labels: ✨ feat

#88 fix : 포스트 전체 조회 오류 수정
  src/main/java/com/album2me/repost/domain/post/controller/PostController.java
  src/main/java/com/album2me/repost/domain/post/repository/PostCustomRepository.java
  src/main/java/com/album2me/repost/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/album2me/repost/domain/post/service/PostService.java
Labels: 🐛 fix

#91 feat: RefreshToken 구현
  src/main/java/com/album2me/repost/domain/auth/dto/response/AuthenticationResponse.java
  src/main/java/com/album2me/repost/domain/auth/service/AuthService.java
  src/main/java/com/album2me/repost/global/config/redis/RedisConfig.java
  src/main/java/com/album2me/repost/global/config/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/album2me/repost/global/config/security/jwt/JwtProvider.java
Labels: ✨ feat

#92 feat : 갤러리 조회 기능 구현
  src/main/java/com/album2me/repost/domain/image/dto/request/UploadImageRequest.java
  src/main/java/com/album2me/repost/domain/image/dto/request/UploadImageUrlRequest.java
  src/main/java/com/album2me/repost/domain/image/dto/response/ImagePageResponse.java
  src/main/java/com/album2me/repost/domain/image/dto/response/ImageResponse.java
  src/main/java/com/album2me/repost/domain/image/dto/response/UploadImageResponse.java
  src/main/java/com/album2me/repost/domain/image/service/ImageService.java
  src/main/java/com/album2me/repost/domain/post/controller/PostController.java
  src/main/java/com/album2me/repost/domain/post/dto/request/GalleryShowRequest.java
  src/main/java/com/album2me/repost/domain/post/dto/response/GalleryPageResponse.java
  src/main/java/com/album2me/repost/domain/post/dto/response/GalleryResponse.java
  src/main/java/com/album2me/repost/domain/post/repository/PostCustomRepository.java
  src/main/java/com/album2me/repost/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/album2me/repost/domain/post/service/PostService.java
  src/main/java/com/album2me/repost/domain/user/service/UserService.java
Labels: ✨ feat

#103 fix: 커서 방식 페이지네이션 로직 변경
  src/main/java/com/album2me/repost/domain/post/repository/PostCustomRepositoryImpl.java
Labels: 🐛 fix, 🔧 chore
